# Generated by Django 3.0.5 on 2021-07-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100,
                                          verbose_name='Произведение')),
                ('slug', models.SlugField(max_length=100, unique=True,
                                          verbose_name='Слаг произведения')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100,
                                          verbose_name='Жанр')),
                ('slug', models.SlugField(max_length=100, unique=True,
                                          verbose_name='Слаг жанра')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100,
                                          verbose_name='Произведение')),
                ('year', models.PositiveIntegerField(db_index=True, validators=[
                    api.validators.year_validator],
                                                     verbose_name='Год выпуска')),
                ('description',
                 models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='titles',
                                               to='api.Category',
                                               verbose_name='Категория')),
                ('genre', models.ManyToManyField(blank=True, db_index=True,
                                                 related_name='titles',
                                                 to='api.Genre',
                                                 verbose_name='Жанр')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(
                    validators=[api.validators.score_validator])),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True,
                                                  verbose_name='Дата/время отзыва')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='reviews',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор отзыва')),
                ('title',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='reviews', to='api.Title',
                                   verbose_name='Заголовок отзыва')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True,
                                                  verbose_name='Дата/время комментария')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='comments',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор комментария')),
                ('review',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='comments', to='api.Review',
                                   verbose_name='Комментируемый отзыв')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
